# -*- coding: utf-8 -*-
"""model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggZtk1KdoTEeM9jdwItfaZwCc4e13FKO
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

class VendorMatcher:
    def __init__(self, vendors_df):
        self.df = vendors_df
        self.vectorizer = TfidfVectorizer()
        self.tfidf_matrix = self.vectorizer.fit_transform(self.df['parsed_features'])

    # def match(self, category, capabilities, threshold=0.6):
    #     candidates = self.df[self.df['main_category'].str.lower() == category.lower()]

    #     if candidates.empty:
    #         return pd.DataFrame()  # no matches

    #     candidate_features = candidates['parsed_features']
    #     candidate_vectors = self.vectorizer.transform(candidate_features)

    #     query = " ".join(capabilities)
    #     query_vec = self.vectorizer.transform([query])

    #     similarities = cosine_similarity(query_vec, candidate_vectors).flatten()
    #     candidates = candidates.copy()
    #     candidates['similarity'] = similarities

    #     candidates = candidates[candidates['similarity'] >= threshold]

    #     candidates['final_score'] = candidates.apply(
    #         lambda row: self.compute_final_score(row['similarity'], row['rating']),
    #         axis=1
    #     )

    #     return candidates.sort_values(by='final_score', ascending=False)

    def match(self, category, capabilities, threshold=0.6):
        candidates = self.df[self.df['main_category'].str.lower() == category.lower()]
        
        print(f"\n🔎 Found {len(candidates)} vendors in category '{category}'.")

        if candidates.empty:
            print("⚠️ No vendors found for this category.")
            return pd.DataFrame()

        candidate_features = candidates['parsed_features']
        candidate_vectors = self.vectorizer.transform(candidate_features)

        query = " ".join(capabilities)
        print(f"🔎 User query after joining capabilities: '{query}'")

        query_vec = self.vectorizer.transform([query])

        similarities = cosine_similarity(query_vec, candidate_vectors).flatten()
        candidates = candidates.copy()
        candidates['similarity'] = similarities

        print(f"✅ Similarity scores calculated. First few:\n{candidates[['product_name', 'similarity']].head()}")

        candidates = candidates[candidates['similarity'] >= threshold]
        
        print(f"🔎 {len(candidates)} vendors remaining after applying similarity threshold {threshold}.")

        if candidates.empty:
            print("⚠️ No vendors passed similarity threshold.")
            return pd.DataFrame()

        candidates['final_score'] = candidates.apply(
            lambda row: self.compute_final_score(row['similarity'], row['rating']),
            axis=1
        )

        print(f"✅ Final scores calculated. First few:\n{candidates[['product_name', 'final_score']].head()}")

        return candidates.sort_values(by='final_score', ascending=False)

    def compute_final_score(self, similarity, rating):
        normalized_rating = rating / 5.0 if pd.notna(rating) else 0.0
        return 0.7 * similarity + 0.3 * normalized_rating